### ISSUE TITLE
Add "Add Class" API Endpoint - Front End

### ISSUE THREAD

**Issue by leopiresgoss** [WomenPlusPlus/deploy-impact-22-wikimini-c#36]
Connect the front-end state management (Redux) to the API class.

To do that: 

- [x] Check the API documentation with the back-end team
- [x] Create an action to send the data to the API
- [x] Update the state management according to the result

**Comment by leopiresgoss** [comment]
This is the API endpoint that worked in my postman: POST [http://wikimini-c.azurewebsites.net/api.php?action=createclass&class_name=Example-Leo](http://wikimini-c.azurewebsites.net/api.php?action=createclass&class_name=Example-Leo)

Obs.: the teacher id will be added after the registration/login works

**Comment by leopiresgoss** [comment]
It didn't work because we might have to set the CORS config in the server


![Image](https://user-images.githubusercontent.com/61767582/198437861-94dfd958-707b-42b8-9331-a82aa495cef6.png)

**Comment by vichoiglesias** [comment]
I just changed the CORS variable on the backend: @leopiresgoss, could you please try if it works now?

**Comment by leopiresgoss** [comment]
@vichoiglesias thank you. It worked!



![Image](https://user-images.githubusercontent.com/61767582/198574588-f787962d-1918-4c15-87b2-d4940cac647c.png)
